---
- name: Define o arquivo de configuracao do servidor vsftpd no Debian/Ubuntu
  when: ansible_os_family == "Debian"
  template:
    src: vsftpddeb.conf.j2
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart vsftpd
  tags: vsftpd    

- name: Define o arquivo de configuracao do servidor vsftpd no RedHat/CentOS
  when: ansible_os_family == "RedHat"
  template:
    src: vsftpdrhel.conf.j2
    dest: /etc/vsftpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart vsftpd
  tags: vsftpd
