---
- name: java aqui
  become: yes
  apt: name=software-properties-common state=latest

- name: Java Repositorio
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: aceitar a licenca chatenha
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Instala a bagaca
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
